package com.ilionx.nl.reports;

import org.w3c.dom.Document;

import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class XsltTransformer {

    // Global value so it can be ref'd by the tree-adapter
    static Document document;

    public static void main(String[] argv) {
        if (argv.length != 3) {
            System.err.println("Wrong number of arguments: Usage: java Stylizer stylesheet xmlfile resultfile");
            System.exit(1);
        }

        try {
            File stylesheet = new File(argv[0]);
            File datafile = new File(argv[1]);
            File resultFile = new File(argv[2]);

            // Use a Transformer for output
            TransformerFactory tFactory = TransformerFactory.newInstance();
            Transformer transformer = tFactory.newTransformer(new StreamSource(stylesheet));

            transformer.getOutputProperties().setProperty("media-type", "text/html");
            transformer.transform(new StreamSource(datafile), new StreamResult(new FileOutputStream(resultFile)));
        } catch (TransformerConfigurationException tce) {
            // Error generated by the parser
            System.out.println("\n** Transformer Factory error");
            System.out.println("   " + tce.getMessage());

            // Use the contained exception, if any
            Throwable x = tce;

            if (tce.getException() != null) {
                x = tce.getException();
            }

            x.printStackTrace();
        } catch (TransformerException te) {
            // Error generated by the parser
            System.out.println("\n** Transformation error");
            System.out.println("   " + te.getMessage());

            // Use the contained exception, if any
            Throwable x = te;

            if (te.getException() != null) {
                x = te.getException();
            }

            x.printStackTrace();
        } catch (IOException ioe) {
            // I/O error
            ioe.printStackTrace();
        }
    } // main
}
