<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://soap.nl.ilionx.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://soap.nl.ilionx.com/" name="SomeWebserviceService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://soap.nl.ilionx.com/" schemaLocation="http://localhost:60821/someWebservice?xsd=1"/>
        </xsd:schema>
    </types>
    <message name="doSomething">
        <part name="parameters" element="tns:doSomething"/>
    </message>
    <message name="doSomethingResponse">
        <part name="parameters" element="tns:doSomethingResponse"/>
    </message>
    <portType name="SomeWebserviceInterface">
        <operation name="doSomething">
            <input wsam:Action="http://soap.nl.ilionx.com/SomeWebserviceInterface/doSomethingRequest" message="tns:doSomething"/>
            <output wsam:Action="http://soap.nl.ilionx.com/SomeWebserviceInterface/doSomethingResponse" message="tns:doSomethingResponse"/>
        </operation>
    </portType>
    <binding name="SomeWebservicePortBinding" type="tns:SomeWebserviceInterface">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="doSomething">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="SomeWebserviceService">
        <port name="SomeWebservicePort" binding="tns:SomeWebservicePortBinding">
            <soap:address location="http://localhost:60821/someWebservice"/>
        </port>
    </service>
</definitions>